// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQmV5-qZcdqoaaD9DYLT8709nvAXz2XI',
    appId: '1:299053287962:web:ce1ba9d848194358205fa3',
    messagingSenderId: '299053287962',
    projectId: 'userinfo-b1d5d',
    authDomain: 'userinfo-b1d5d.firebaseapp.com',
    storageBucket: 'userinfo-b1d5d.firebasestorage.app',
    measurementId: 'G-XLR59JS9B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0k7QZ75M8DEGS_DvVf-bg2VO9TJWnoM',
    appId: '1:299053287962:android:e095b282010ad730205fa3',
    messagingSenderId: '299053287962',
    projectId: 'userinfo-b1d5d',
    storageBucket: 'userinfo-b1d5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm4YxX0beRYXB-v138KuEKIVt0TiYlONA',
    appId: '1:299053287962:ios:cbd689f5330269a9205fa3',
    messagingSenderId: '299053287962',
    projectId: 'userinfo-b1d5d',
    storageBucket: 'userinfo-b1d5d.firebasestorage.app',
    androidClientId: '299053287962-s3rp8tio2h561usvv4vvp01ahrbln076.apps.googleusercontent.com',
    iosClientId: '299053287962-s8viflm8gtgmo2d1iauv1d8ctof8rf64.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm4YxX0beRYXB-v138KuEKIVt0TiYlONA',
    appId: '1:299053287962:ios:cbd689f5330269a9205fa3',
    messagingSenderId: '299053287962',
    projectId: 'userinfo-b1d5d',
    storageBucket: 'userinfo-b1d5d.firebasestorage.app',
    androidClientId: '299053287962-s3rp8tio2h561usvv4vvp01ahrbln076.apps.googleusercontent.com',
    iosClientId: '299053287962-s8viflm8gtgmo2d1iauv1d8ctof8rf64.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQmV5-qZcdqoaaD9DYLT8709nvAXz2XI',
    appId: '1:299053287962:web:5991e680c1a78b04205fa3',
    messagingSenderId: '299053287962',
    projectId: 'userinfo-b1d5d',
    authDomain: 'userinfo-b1d5d.firebaseapp.com',
    storageBucket: 'userinfo-b1d5d.firebasestorage.app',
    measurementId: 'G-6DD7MRCBVC',
  );
}
